"""empty message

Revision ID: 387b3156ee76
Revises: 
Create Date: 2025-12-30 22:48:41.963150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '387b3156ee76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cedula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestaalumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correcta', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta')
    op.drop_table('respuestaalumno')
    op.drop_table('pregunta')
    op.drop_table('alumno')
    # ### end Alembic commands ###
